name: Deploy Hashicorp Vault

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: hostinger
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy image
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d
          docker image prune -f